Browser: fix crash updating recycled favicon
Occurs on the (slow) galaxysmtd.

java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalStateException: Can't compress a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:345)
	at android.graphics.Bitmap.compress(Bitmap.java:985)
	at com.android.browser.Bookmarks$1.doInBackground(Bookmarks.java:206)
	at com.android.browser.Bookmarks$1.doInBackground(Bookmarks.java:202)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

Change-Id: I867696996c786024aabb869583583198ac3bc13a